services:
  db:
    build: docker/db
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    env_file: backend/.env
    volumes:
      - ./backend:/backend
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db

volumes:
  db-data:
